version: '3.9'
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
      - --port ${REDIS_PORT}
    env_file:
      - .env
    restart: on-failure
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  schedule:
    build: .
    command: sh -c "python -m monitoring"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    volumes:
      - snapshots:/app/bot/snapshots
  bot:
    build: .
    command: sh -c "python -m run"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    volumes:
      - snapshots:/app/bot/snapshots

volumes:
  snapshots: